### ISSUE TITLE
Does the benchmark support python3.12?

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/superbenchmark#704]
When I use python 3.12, I encountered below issue. Does the benchmark support python3.12? if no, when it will support python 3.12? Thanks!

```
python3 -m pip install .
Processing /home/lisatest/superbenchmark
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/lisatest/venv/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/home/lisatest/venv/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/home/lisatest/venv/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by netllama** [comment]
Also doesn't work with `3.11` for the same reason.

**Comment by polarG** [comment]
@LiliDeng what's version were you using? py3.12 only support by the main branch. We are releasing v0.12.0 and it will support 3.12.
