### PR TITLE
Bugfix - gpu_stream: remove ROCm build support, require CUDA with NVML

### PR DESCRIPTION
**Pull request by polarG**
Summary

  The gpu_stream benchmark has NVIDIA-specific dependencies that prevent it from compiling on ROCm 6.3+. This change makes it CUDA-only, gracefully skipping the build with a warning on non-NVIDIA
  environments.

  Problem

  The gpu_stream benchmark fails to compile on ROCm 6.3+ due to multiple NVIDIA-specific dependencies:

   1. nvml.h — NVIDIA Management Library header, used for querying actual memory clock rates. No HIP equivalent. Referenced in gpu_stream.cu and gpu_stream_utils.hpp.
   2. cuda.h in headers — Three .hpp files (gpu_stream.hpp, gpu_stream_kernels.hpp, gpu_stream_utils.hpp) directly include <cuda.h> and <cuda_runtime.h>. These headers are not processed by hipify-perl (only
  .cu source files are), so they fail to resolve on ROCm.
   3. Deprecated hipDeviceProp_t struct fields — The code accesses memoryBusWidth, memoryClockRate, and ECCEnabled from the device properties struct. These fields were removed from hipDeviceProp_t in ROCm
    6.3, causing compilation errors after hipification.

  The existing ROCm path was marked as incomplete (# TODO: test for ROC) and was never fully functional on recent ROCm versions.

  Changes

   - Removed the non-functional ROCm/HIP build path from gpu_stream/CMakeLists.txt
   - When CUDA is not found, prints a warning and returns gracefully instead of attempting a broken hipify build or raising FATAL_ERROR
   - No changes to the NVIDIA/CUDA build path — it continues to work as before

  Impact

   - NVIDIA builds: No change — gpu_stream builds and installs normally
   - ROCm builds: gpu_stream is skipped with a warning message. Previously it would fail the entire make cppbuild step, blocking the Docker image build
   - Other benchmarks: Unaffected — build.sh continues to the next benchmark after gpu_stream returns

### CODE REVIEW

**Review by WenqingLan1 — APPROVED** [review]

**Review by guoshzhao — APPROVED** [review]

File: superbench/benchmarks/micro_benchmarks/gpu_stream/CMakeLists.txt [hunk 1]
```diff
@@ -31,30 +31,8 @@ if(CUDAToolkit_FOUND)
...
-            target_compile_definitions(gpu_stream PRIVATE HIP_UNCACHED_MEMORY)
-        endif()
-
-        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2")
-        target_link_libraries(gpu_stream numa hip::device)
-    else()
-        message(FATAL_ERROR "No CUDA or ROCm environment found.")
-    endif()
+    message(WARNING "gpu_stream: CUDA not found, skipping build (requires NVIDIA GPU with NVML)")
+    return()
```
[the remark this answers is not in the document]
Comment (polarG) [reply superbench/benchmarks/micro_benchmarks/gpu_stream/CMakeLists.txt]: Addressed — added an explicit `find_library(NVML_LIBRARY nvidia-ml ...)` check that runs after `CUDAToolkit_FOUND`. If NVML is not found, the build now skips with a warning instead of proceeding to a link-time failure. The discovered library path is used via `${NVML_LIBRARY}` instead of the bare `nvidia-ml` name.

The search includes `PATH_SUFFIXES stubs` intentionally — CUDA toolkit ships stub libraries for cross-compilation and CI builds on machines without a physical GPU/driver. Linking against the stub is the standard CUDA practice for build-time resolution; the real `libnvidia-ml.so` is loaded at runtime from the driver.

File: superbench/benchmarks/micro_benchmarks/gpu_stream/CMakeLists.txt [hunk 2]
```diff
@@ -31,30 +31,8 @@ if(CUDAToolkit_FOUND)
...
 endif()
 
 install(TARGETS gpu_stream RUNTIME DESTINATION bin)
```
[the remark this answers is not in the document]
Comment (polarG) [reply superbench/benchmarks/micro_benchmarks/gpu_stream/CMakeLists.txt]: Addressed — changed the registration to `platform=Platform.CUDA` so `gpu-stream` is only available on NVIDIA platforms, consistent with other CUDA-only benchmarks like `nvbandwidth`, `cublas-function`, `cudnn-function`, etc.

Also removed the ROCm test cases from `test_gpu_stream.py` since they are no longer applicable.

Did not adopt the stub-script approach — since the benchmark is now not registered on ROCm at all, the runner will never attempt to invoke it on non-CUDA platforms, so there is no "binary not found" path to hit.
